export const MUSICXML_LOADED = "MUSICXML_LOADED";
export const MIDIFILE_LOADED = "MIDIFILE_LOADED";
export const MUSICXML_SELECTED = "MUSICXML_SELECTED";
export const MIDIFILE_SELECTED = "MIDIFILE_SELECTED";
export const SET_TRANSPORT = "SET_TRANSPORT";
export const SET_PROGRESS = "SET_PROGRESS";
export const SET_NOTEMAPPING = "SET_NOTEMAPPING";

export const INITIALIZING = "INITIALIZING";
export const LOAD_INIT_DATA = "LOAD_INIT_DATA";
export const INIT_DATA_LOADED = "INIT_DATA_LOADED";
export const SCORE_READY = "SCORE_READY";
export const SONG_READY = "SONG_READY";
export const UPDATE_SONG_ACTION = "UPDATE_SONG_ACTION";
export const UPLOAD_XMLDOC = "UPLOAD_XMLDOC";
export const UPLOAD_MIDIFILE = "UPLOAD_MIDIFILE";
export const UPDATE_NOTE_MAPPING = "UPDATE_NOTE_MAPPING";
export const POSITION_SLIDER_CHANGED = "POSITION_SLIDER_CHANGED";
export const PLAYHEAD_SEEKING = "PLAYHEAD_SEEKING";
export const UPDATE_PLAYHEAD_MILLIS = "UPDATE_PLAYHEAD_MILLIS";

// when user clicks on note in score
export const SELECTED_NOTE = "SELECTED_NOTE";
